(function () {
    window.App = window.App || {};
    const existingState = window.App.state || {};

    const defaultState = {
        appLang: 'en',
        lang: 'en',
        myTests: [],
        incomingOffers: [],
        myProjects: [],
        mutualSeeking: [],
        mutualPrelaunch: [],
        mutualReturns: [],
        guestProjects: [],
        bountyContracts: [],
        communityEvents: null,
        eventsExpanded: false,
        activeTimerAppId: null,
        _timerEndTimestamp: null,
        _timerIntervalId: null,
        _timerIsScreenshot: false,
        _timerOwnerUsername: '',
        _timerLocalDate: '',
        _timerStorageKey: 'devtest_active_timer',
        _timerReadyStateKey: 'devtest_timer_ready_state_v1',
        _timerReadyState: {},
        _firstDayScreenshotStateKey: 'devtest_firstday_screenshot_state_v1',
        _firstDayScreenshotState: {},
        pendingProjectData: null,
        projectToEdit: null,
        _transferProjectId: null,
        _transferTargetUser: null,
        visibilityStats: {},
        _activeRequests: 0,
        _karmaAppId: null,
        _karmaTesterId: null,
        _karmaDistributionProjectId: null,
        _offersTimerId: null,
        _reportAppId: null,
        _reportOwnerUsername: null,
        _issueReportAppId: null,
        _userEmail: '',
        _pendingScreenshotReminderUsername: null,
        _dropTestAppId: null,
        _leaveMutualAppId: null,
        _leaveMutualStats: null,
        _kickTarget: null,
        _overtimeTest: null,
        _syncProjectId: null,
        _socialBonusStatus: 'none',
        _earnGrantCount: 0,
        _earnGrantBust: 0,
        _earnReferralBust: 0,
        _earnGuestInviteCount: 0,
        _earnGuestInviteBust: 0,
        _earnExchangeBust: 0,
        _earnRetentionBust: 0,
        _earnEarlyFinishCount: 0,
        _earnEarlyFinishBust: 0,
        _earnFeedbackCount: 0,
        _earnFeedbackBust: 0,
        _earnPlayReviewCount: 0,
        _earnPlayReviewBust: 0,
        _earnSprintJoined: 0,
        _earnSprintBust: 0,
        _feedbackType: 'bug',
        _inviteProjectId: null,
        archivedProjects: [],
        projectToDelete: null,
        _activeProjectFeedbackAppId: null,
        _activeProjectFeedbackItems: [],
        _activeProjectFeedbackArchived: false,
        _feedbackRewardTargetId: null,
        _feedbackRewardBust: 0,
        _feedbackRewardKarma: 0,
        myProjectsLoadError: false,
        marketCache: null,
        MARKET_CACHE_KEY: 'market_cache_v1',
        GUEST_PROJECTS_CACHE_KEY: 'guest_projects_cache_v1',
        EXTERNAL_COUNTS_CACHE_KEY: 'external_counts_cache_v1',
        _lastFetchTimes: { mutual: 0, bounty: 0, tests: 0, projects: 0, offers: 0, archived: 0, reliabilitySummary: 0, reliabilityBreakdown: 0 },
        MARKET_FETCH_THROTTLE_MS: 15000,
        TESTS_FETCH_THROTTLE_MS: 20000,
        PROJECTS_FETCH_THROTTLE_MS: 30000,
        OFFERS_FETCH_THROTTLE_MS: 15000,
        ARCHIVED_FETCH_THROTTLE_MS: 45000,
        RELIABILITY_FETCH_THROTTLE_MS: 30000,
        EXTERNAL_COUNTS_CACHE_TTL_MS: 10 * 60 * 1000,
        SYNC_CONFIRMATION_DELAY_MS: 450,
        _marketInFlight: { mutual: null, bounty: null },
        OFFERS_CACHE_KEY: 'incoming_offers_cache_v1',
        _offersInFlight: null,
        _offersLoadError: false,
        _offersLoadedOnce: false,
        _offersPollId: null,
        _blockedOfferProjectsByOwner: {},
        TESTS_CACHE_KEY: 'tests_cache_v1',
        myTestsCache: null,
        _testsInFlight: null,
        _testsLoadedOnce: false,
        PROJECTS_CACHE_KEY: 'projects_cache_v1',
        myProjectsCache: null,
        _projectsInFlight: null,
        _projectsLoadedOnce: false,
        RELIABILITY_SUMMARY_CACHE_KEY: 'reliability_summary_cache_v1',
        RELIABILITY_BREAKDOWN_CACHE_KEY: 'reliability_breakdown_cache_v1',
        reliabilitySummaryCache: null,
        reliabilityBreakdownCache: null,
        reliabilitySummary: null,
        reliabilityBreakdown: null,
        _reliabilitySummaryInFlight: null,
        _reliabilityBreakdownInFlight: null,
        _reliabilitySummaryLoadedOnce: false,
        _reliabilityBreakdownLoadedOnce: false,
        _reliabilitySummaryLoadError: false,
        _reliabilityBreakdownLoadError: false,
        _pendingActions: new Set(),
        _autoAcceptMutualEnabled: false,
        _autoAcceptToggleInFlight: false,
        _attachDeviceInfoToBugs: true,
        _deviceInfo: '',
        _deviceInfoIsManual: false,
        _deviceInfoLoaded: false,
        _deviceProfileComplete: false,
        _deviceProfileRewardClaimed: false,
        _deviceProfileBustEarned: 0,
        _deviceProfileBannerReady: false,
        _pendingInitialHighlightTestId: null,
        _highlightTestTimerId: null,
        _backgroundSyncState: { tests: 0, projects: 0, market: 0 },
        _deferredBootstrapStarted: false,
        _initialRouteHandled: false,
        _marketPollId: null,
        MARKET_POLL_INTERVAL_MS: 5 * 60 * 1000,
        _marketFeedState: {
        mutual: { confirmedEmpty: false, emptyStreak: 0 },
        bounty: { confirmedEmpty: false, emptyStreak: 0 }
    },
        _marketRetryTimers: { mutual: null, bounty: null },
        _marketForceSkeleton: false,
        _guestProjectsInFlight: null,
        _guestProjectsLoadedOnce: false,
        _guestProjectsExpanded: false,
        _guestProjectsLoadError: false,
        _externalCountsInFlight: null,
        _externalCountsLoadedOnce: false,
        _externalCounts: { leads_count: 0, guest_projects_count: 0, updated_at: 0 },
        _guestProjectsVisibleCount: 5,
        _guestProjectsFilters: { lang: 'ALL', category: 'ALL' },
        _guestProjectsAvailableLangs: [],
        _guestProjectTargetHighlightTimer: null,
        _postSyncToastSuppressionUntil: 0,
        POST_SYNC_TOAST_SUPPRESSION_MS: 8000,
    };

    window.App.state = Object.assign(defaultState, existingState);

    window.App.bindStateProperty = function (name, getValue, setValue) {
        Object.defineProperty(window.App.state, name, {
            enumerable: true,
            configurable: true,
            get: getValue,
            set: setValue,
        });
    };
})();
