/* Phase 4.4 — ui.js facade (re-exports for backward compatibility) */
/* All functions are now defined in ui/ui-*.js modules. */
/* This file exists only for Object.assign(window, {...}) re-exports. */

Object.assign(window, {
    showSkeleton,
    showRetry,
    formatTimeAgo,
    getAvatar,
    renderIcon,
    formatOfferRemaining,
    renderProjects,
    openOvertimeModal,
    closeOvertimeModal,
    overtimeContactOwner,
    openKickTesterModal,
    closeKickTesterModal,
    toggleKickReasonOther,
    openSyncModal,
    closeSyncModal,
    openProtectionCenter,
    closeProtectionCenter,
    _ppcUpdateCalculations,
    _ppcChangeTip,
    _ppcAddTip,
    _ppcSwitchToEditMode,
    _renderProtectionCenterState1,
    _renderProtectionCenterState2,
    renderArchivedProjects,
    toggleArchive,
    showScreenshotDayAlert,
    showVisibilityToast,
    renderVisibilityModeModal,
    openVisibilityModeModal,
    closeVisibilityModeModal,
    applyVisibilityModeFromModal,
    handleMassInviteAction,
    openInviteModal,
    setInviteMode,
    escapeForAttr,
    copyAndAction,
    publishProjectToMarketAction,
    closeInviteModal,
    openDeleteModal,
    closeDeleteModal,
    openModal,
    closeModal,
    switchGroupTab,
    closeEmailWarningModal,
    showReadonlyAlert,
    openEditModal,
    closeEditModal,
    openImageZoom,
    closeImageZoom,
    escapeHTML: window.escapeHTML,
    copyEmail,
    openProjectDetailsModal,
    closeProjectDetailsModal,
});

Object.assign(window.ui, {
    showLoading,
    hideLoading,
    showGuestTestsInfoAlert,
    triggerGuestShowcaseNavigation,
});
